<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <RootNamespace>GameServerControl.Client</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
    <AssemblyName>GameServerControl</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\logo.ico" />
    <None Include="Assets\logo.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameServerControl.Shared\GameServerControl.Shared.csproj" />
  </ItemGroup>
</Project>
